name: DonPhds Gradle Package Release

#on:
#  pull_request_target:
#    types:
#      - closed
#jobs:
#  project:
#    uses: donphds-auth/build/.github/workflows/gradle-publish.yml@master
#    secrets:
#      OSSRH_USER: ${{ secrets.OSSRH_USER }}
#      OSSRH_PASSWD: ${{ secrets.OSSRH_PASSWD }}
#      SECRET_KET_ID: ${{secrets.SECRET_KET_ID}}
#      SECRET_KET_RING_FILE_BASE64: ${{secrets.SECRET_KET_RING_FILE_BASE64}}


on:
  push

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: |
          ./gradlew build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: publish to maven central
        working-directory: ./artifact
        run: |
          pwd && ls -a
          echo ${{secrets.SECRET_KET_RING_FILE_BASE64}} > ./.gradle/secring.gpg.b64
          base64 -d ./.gradle/secring.gpg.b64 > ./.gradle/secring.gpg
          cat  ./.gradle/secring.gpg
          chmod +x ./gradlew
          ./gradlew publish -Psigning.keyId=${{ secrets.SECRET_KET_ID }} -Psigning.password=${{ secrets.SECRET_KET_PASSWD }} -Psigning.secretKeyRingFile=./.gradle/secring.gpg
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWD: ${{ secrets.OSSRH_PASSWD }}